
dist: trusty
os: linux
language: cpp
sudo: required

branches:
    only:
        - master
        - travis

env:
    global:
        - CUDA_VERSION=8.0.61-1
        - CUDA_VERSION_SHORT=8.0
        #- GEARSHIFFT_CLFFT_VERSION=v2.12.2
        - CLANG_VERSION=3.8

cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - cmake
            - opencl-headers

matrix:
    include:
        - name: Clang-3.8 CUDA-8.0.61 Boost-1.60.0 FFTW3 Release
          compiler: clang
          env: GEARSHIFFT_BUILD_TYPE=Release
        - name: g++-5 CUDA-8.0.61 Boost-1.60.0 FFTW3 Release
          compiler: gcc
          env: GEARSHIFFT_BUILD_TYPE=Release
        - name: g++-5 CUDA-8.0.61 Boost-1.60.0 FFTW3 Debug
          compiler: gcc
          env: GEARSHIFFT_BUILD_TYPE=Debug

before_install:
    - set -e
    - travis_retry sudo apt-get install -qq g++-5
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - |
      CUDA_CACHE_PATH=${TRAVIS_BUILD_DIR}/deps/cuda-${CUDA_VERSION_SHORT}
      mkdir -p ${CUDA_CACHE_PATH}
      if [[ -z "$(ls -A ${CUDA_CACHE_PATH})" ]]; then
        travis_retry wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1404-8-0-local-ga2_${CUDA_VERSION}_amd64-deb -q -O "${CUDA_CACHE_PATH}/cuda.deb";
      else
        echo "Using cached cuda.deb in $CUDA_CACHE_PATH"
      fi
      travis_retry sudo dpkg -i ${CUDA_CACHE_PATH}/cuda.deb
      travis_retry sudo apt-get update -qq
      CUDA_APT=${CUDA_VERSION_SHORT/./-}
      travis_retry sudo apt-get install -qy cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-${CUDA_APT} cuda-cufft-dev-${CUDA_APT}

install:
    - if [ "${CXX}" == "g++" ]; then export CXX=g++-5; export CC=${CXX/g++/gcc}; export GCOV=${CXX/g++/gcov}; fi
    - if [ "${CXX}" == "clang++" ]; then export CXX=clang++-${CLANG_VERSION}; export CC=clang-${CLANG_VERSION}; export GCOV="gcov"; fi
    # Boost [is now done via gearshifft cmake]
    # CUDA
    - |
      export CUDA_ROOT=/usr/local/cuda-${CUDA_VERSION_SHORT}
      export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:${LD_LIBRARY_PATH}
      export PATH=${CUDA_ROOT}/bin:${PATH}

    # Versions
    - $CXX --version
    - nvcc --version
    - cmake --version

script:
    - mkdir build && cd build
    - set -e
    - |
      cmake -DCMAKE_BUILD_TYPE=${GEARSHIFFT_BUILD_TYPE} \
            -DGEARSHIFFT_VERBOSE=ON \
            -DGEARSHIFFT_TESTS_ADD_CPU_ONLY=ON \
            -DGEARSHIFFT_SUPERBUILD_EXT_INBUILD=ON \
            -DGEARSHIFFT_SUPERBUILD_EXT_DIR=${TRAVIS_BUILD_DIR}/deps \
            -DGEARSHIFFT_USE_STATIC_LIBS=OFF \
            -DGEARSHIFFT_SUPERBUILD_EXT_DOWNLOAD_Boost=ON \
            -DGEARSHIFFT_SUPERBUILD_EXT_DOWNLOAD_CLFFT=OFF \
            -DGEARSHIFFT_SUPERBUILD_EXT_DOWNLOAD_FFTW=ON \
            ..
      make gearshifft -j 2
      cd gearshifft-build
      ctest --output-on-failure
    - set +e

notifications:
    email: false
